# Generated by Django 4.1.3 on 2022-11-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_User',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True)),
                ('card_number', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_User_details',
            fields=[
                ('user_details', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('salary', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_user_details', to='todo_app.test_user')),
            ],
        ),
    ]
