# Generated by Django 4.1.3 on 2022-11-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_Task',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('task_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='test_user_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='Test_User',
        ),
        migrations.DeleteModel(
            name='Test_User_details',
        ),
    ]
